# Generated by Django 4.2.14 on 2025-01-21 21:28

from django.db import migrations, models
import django.db.models.deletion
import times.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0016_movielist_movelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
    ]
